# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realsence_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='realsence_service.proto',
  package='ocr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17realsence_service.proto\x12\x03ocr\"A\n\x0cRequestImage\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\"%\n\x0fReplyCharacters\x12\x12\n\ncharacters\x18\x01 \x03(\t2J\n\x11service_realsence\x12\x35\n\x08OcrImage\x12\x11.ocr.RequestImage\x1a\x14.ocr.ReplyCharacters\"\x00\x62\x06proto3'
)




_REQUESTIMAGE = _descriptor.Descriptor(
  name='RequestImage',
  full_name='ocr.RequestImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ocr.RequestImage.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ocr.RequestImage.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='ocr.RequestImage.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=97,
)


_REPLYCHARACTERS = _descriptor.Descriptor(
  name='ReplyCharacters',
  full_name='ocr.ReplyCharacters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='characters', full_name='ocr.ReplyCharacters.characters', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['RequestImage'] = _REQUESTIMAGE
DESCRIPTOR.message_types_by_name['ReplyCharacters'] = _REPLYCHARACTERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestImage = _reflection.GeneratedProtocolMessageType('RequestImage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTIMAGE,
  '__module__' : 'realsence_service_pb2'
  # @@protoc_insertion_point(class_scope:ocr.RequestImage)
  })
_sym_db.RegisterMessage(RequestImage)

ReplyCharacters = _reflection.GeneratedProtocolMessageType('ReplyCharacters', (_message.Message,), {
  'DESCRIPTOR' : _REPLYCHARACTERS,
  '__module__' : 'realsence_service_pb2'
  # @@protoc_insertion_point(class_scope:ocr.ReplyCharacters)
  })
_sym_db.RegisterMessage(ReplyCharacters)



_SERVICE_REALSENCE = _descriptor.ServiceDescriptor(
  name='service_realsence',
  full_name='ocr.service_realsence',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=138,
  serialized_end=212,
  methods=[
  _descriptor.MethodDescriptor(
    name='OcrImage',
    full_name='ocr.service_realsence.OcrImage',
    index=0,
    containing_service=None,
    input_type=_REQUESTIMAGE,
    output_type=_REPLYCHARACTERS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE_REALSENCE)

DESCRIPTOR.services_by_name['service_realsence'] = _SERVICE_REALSENCE

# @@protoc_insertion_point(module_scope)
