
data = {'Data': ['<?xml version="1.0" encoding="utf-8"?><Doc><ShipmentNos><NO_STORE><![CDATA[019914]]></NO_STORE><NO_ECCODE1><![CDATA[797110947]]></NO_ECCODE1><NO_ECCODE2><![CDATA[4578998330000076]]></NO_ECCODE2><NO_ECCODE3><![CDATA[]]></NO_ECCODE3><AM_SALE><![CDATA[0]]></AM_SALE><NM_ORDWEB><![CDATA[蝦皮購物]]></NM_ORDWEB><NM_ORDER><![CDATA[測試者]]></NM_ORDER><DT_ROPEN><![CDATA[20211003]]></DT_ROPEN><DT_RCLOSE><![CDATA[20211005]]></DT_RCLOSE><NO_LGCODE><![CDATA[17970011045789983-]]></NO_LGCODE><DT_DOWNLOAD><![CDATA[20210928]]></DT_DOWNLOAD><LV_DEGREE><![CDATA[]]></LV_DEGREE><NO_ECBARGET><![CDATA[SHP1410328116]]></NO_ECBARGET><ID_CARDPRT><![CDATA[2]]></ID_CARDPRT><ID_GOODDC><![CDATA[2]]></ID_GOODDC><ID_RETDC><![CDATA[2]]></ID_RETDC><ID_TELCODE><![CDATA[000]]></ID_TELCODE><NO_DLVCFM><![CDATA[999999]]></NO_DLVCFM><NO_RFID><![CDATA[]]></NO_RFID><PASSWORD><![CDATA[]]></PASSWORD><FU_SPACE1><![CDATA[]]></FU_SPACE1><FU_SPACE2><![CDATA[]]></FU_SPACE2><FU_SPACE3><![CDATA[]]></FU_SPACE3><FU_SPACE4><![CDATA[]]></FU_SPACE4><FU_SPACE5><![CDATA[]]></FU_SPACE5><FU_SPACE6><![CDATA[]]></FU_SPACE6><FU_SPACE7><![CDATA[]]></FU_SPACE7><FU_SPACE8><![CDATA[]]></FU_SPACE8><FU_SPACE9><![CDATA[]]></FU_SPACE9><FU_SPACE10><![CDATA[]]></FU_SPACE10></ShipmentNos><ShipmentNos><NO_STORE><![CDATA[019914]]></NO_STORE><NO_ECCODE1><![CDATA[486017826]]></NO_ECCODE1><NO_ECCODE2><![CDATA[1650069610069966]]></NO_ECCODE2><NO_ECCODE3><![CDATA[]]></NO_ECCODE3><AM_SALE><![CDATA[699]]></AM_SALE><NM_ORDWEB><![CDATA[詩詩商行]]></NM_ORDWEB><NM_ORDER><![CDATA[測試者]]></NM_ORDER><DT_ROPEN><![CDATA[20211003]]></DT_ROPEN><DT_RCLOSE><![CDATA[20211005]]></DT_RCLOSE><NO_LGCODE><![CDATA[14860001716500696H]]></NO_LGCODE><DT_DOWNLOAD><![CDATA[20210928]]></DT_DOWNLOAD><LV_DEGREE><![CDATA[]]></LV_DEGREE><NO_ECBARGET><![CDATA[4860066500696]]></NO_ECBARGET><ID_CARDPRT><![CDATA[2]]></ID_CARDPRT><ID_GOODDC><![CDATA[2]]></ID_GOODDC><ID_RETDC><![CDATA[2]]></ID_RETDC><ID_TELCODE><![CDATA[000]]></ID_TELCODE><NO_DLVCFM><![CDATA[999999]]></NO_DLVCFM><NO_RFID><![CDATA[]]></NO_RFID><PASSWORD><![CDATA[]]></PASSWORD><FU_SPACE1><![CDATA[]]></FU_SPACE1><FU_SPACE2><![CDATA[]]></FU_SPACE2><FU_SPACE3><![CDATA[]]></FU_SPACE3><FU_SPACE4><![CDATA[]]></FU_SPACE4><FU_SPACE5><![CDATA[]]></FU_SPACE5><FU_SPACE6><![CDATA[]]></FU_SPACE6><FU_SPACE7><![CDATA[]]></FU_SPACE7><FU_SPACE8><![CDATA[]]></FU_SPACE8><FU_SPACE9><![CDATA[]]></FU_SPACE9><FU_SPACE10><![CDATA[]]></FU_SPACE10></ShipmentNos><ShipmentNos><NO_STORE><![CDATA[019914]]></NO_STORE><NO_ECCODE1><![CDATA[486017826]]></NO_ECCODE1><NO_ECCODE2><![CDATA[1650182410198303]]></NO_ECCODE2><NO_ECCODE3><![CDATA[]]></NO_ECCODE3><AM_SALE><![CDATA[1983]]></AM_SALE><NM_ORDWEB><![CDATA[詩詩商行]]></NM_ORDWEB><NM_ORDER><![CDATA[測試者]]></NM_ORDER><DT_ROPEN><![CDATA[20211003]]></DT_ROPEN><DT_RCLOSE><![CDATA[20211005]]></DT_RCLOSE><NO_LGCODE><![CDATA[14860001716501824B]]></NO_LGCODE><DT_DOWNLOAD><![CDATA[20210928]]></DT_DOWNLOAD><LV_DEGREE><![CDATA[]]></LV_DEGREE><NO_ECBARGET><![CDATA[4860066501824]]></NO_ECBARGET><ID_CARDPRT><![CDATA[2]]></ID_CARDPRT><ID_GOODDC><![CDATA[2]]></ID_GOODDC><ID_RETDC><![CDATA[2]]></ID_RETDC><ID_TELCODE><![CDATA[000]]></ID_TELCODE><NO_DLVCFM><![CDATA[999999]]></NO_DLVCFM><NO_RFID><![CDATA[]]></NO_RFID><PASSWORD><![CDATA[]]></PASSWORD><FU_SPACE1><![CDATA[]]></FU_SPACE1><FU_SPACE2><![CDATA[]]></FU_SPACE2><FU_SPACE3><![CDATA[]]></FU_SPACE3><FU_SPACE4><![CDATA[]]></FU_SPACE4><FU_SPACE5><![CDATA[]]></FU_SPACE5><FU_SPACE6><![CDATA[]]></FU_SPACE6><FU_SPACE7><![CDATA[]]></FU_SPACE7><FU_SPACE8><![CDATA[]]></FU_SPACE8><FU_SPACE9><![CDATA[]]></FU_SPACE9><FU_SPACE10><![CDATA[]]></FU_SPACE10></ShipmentNos><ShipmentNos><NO_STORE><![CDATA[019914]]></NO_STORE><NO_ECCODE1><![CDATA[797110947]]></NO_ECCODE1><NO_ECCODE2><![CDATA[4571930210043501]]></NO_ECCODE2><NO_ECCODE3><![CDATA[]]></NO_ECCODE3><AM_SALE><![CDATA[435]]></AM_SALE><NM_ORDWEB><![CDATA[蝦皮購物]]></NM_ORDWEB><NM_ORDER><![CDATA[測試者]]></NM_ORDER><DT_ROPEN><![CDATA[20211003]]></DT_ROPEN><DT_RCLOSE><![CDATA[20211005]]></DT_RCLOSE><NO_LGCODE><![CDATA[17970011045719302E]]></NO_LGCODE><DT_DOWNLOAD><![CDATA[20210928]]></DT_DOWNLOAD><LV_DEGREE><![CDATA[]]></LV_DEGREE><NO_ECBARGET><![CDATA[SHP2263051944]]></NO_ECBARGET><ID_CARDPRT><![CDATA[2]]></ID_CARDPRT><ID_GOODDC><![CDATA[2]]></ID_GOODDC><ID_RETDC><![CDATA[2]]></ID_RETDC><ID_TELCODE><![CDATA[000]]></ID_TELCODE><NO_DLVCFM><![CDATA[999999]]></NO_DLVCFM><NO_RFID><![CDATA[]]></NO_RFID><PASSWORD><![CDATA[]]></PASSWORD><FU_SPACE1><![CDATA[]]></FU_SPACE1><FU_SPACE2><![CDATA[]]></FU_SPACE2><FU_SPACE3><![CDATA[]]></FU_SPACE3><FU_SPACE4><![CDATA[]]></FU_SPACE4><FU_SPACE5><![CDATA[]]></FU_SPACE5><FU_SPACE6><![CDATA[]]></FU_SPACE6><FU_SPACE7><![CDATA[]]></FU_SPACE7><FU_SPACE8><![CDATA[]]></FU_SPACE8><FU_SPACE9><![CDATA[]]></FU_SPACE9><FU_SPACE10><![CDATA[]]></FU_SPACE10></ShipmentNos><ShipmentNos><NO_STORE><![CDATA[019914]]></NO_STORE><NO_ECCODE1><![CDATA[797110947]]></NO_ECCODE1><NO_ECCODE2><![CDATA[4576760810157232]]></NO_ECCODE2><NO_ECCODE3><![CDATA[]]></NO_ECCODE3><AM_SALE><![CDATA[1572]]></AM_SALE><NM_ORDWEB><![CDATA[蝦皮購物]]></NM_ORDWEB><NM_ORDER><![CDATA[測試者]]></NM_ORDER><DT_ROPEN><![CDATA[20211003]]></DT_ROPEN><DT_RCLOSE><![CDATA[20211005]]></DT_RCLOSE><NO_LGCODE><![CDATA[17970011045767608Q]]></NO_LGCODE><DT_DOWNLOAD><![CDATA[20210928]]></DT_DOWNLOAD><LV_DEGREE><![CDATA[]]></LV_DEGREE><NO_ECBARGET><![CDATA[SHP2627373313]]></NO_ECBARGET><ID_CARDPRT><![CDATA[2]]></ID_CARDPRT><ID_GOODDC><![CDATA[2]]></ID_GOODDC><ID_RETDC><![CDATA[2]]></ID_RETDC><ID_TELCODE><![CDATA[000]]></ID_TELCODE><NO_DLVCFM><![CDATA[999999]]></NO_DLVCFM><NO_RFID><![CDATA[]]></NO_RFID><PASSWORD><![CDATA[]]></PASSWORD><FU_SPACE1><![CDATA[]]></FU_SPACE1><FU_SPACE2><![CDATA[]]></FU_SPACE2><FU_SPACE3><![CDATA[]]></FU_SPACE3><FU_SPACE4><![CDATA[]]></FU_SPACE4><FU_SPACE5><![CDATA[]]></FU_SPACE5><FU_SPACE6><![CDATA[]]></FU_SPACE6><FU_SPACE7><![CDATA[]]></FU_SPACE7><FU_SPACE8><![CDATA[]]></FU_SPACE8><FU_SPACE9><![CDATA[]]></FU_SPACE9><FU_SPACE10><![CDATA[]]></FU_SPACE10></ShipmentNos></Doc>'], 'ApiKey': ['rPhC3chnke0l7oSDDYCA3iaunyj48g40l7oDDYCALVKqZF73VXAkxDkeFOapnwyCTv6BlOCAkxDQnwNTmeEHUEHUDDwk9uJCnlGVpJabJqf9eQwvdecJ1LVKVX7HbbJJ'], 'TimeStamp': ['16330827708329119'], 'Signature': ['0b9c5eced5c8a5f3913ab1b11bd484df29b059a85bd884da20f684fab63a5c6f63c38f3dea1cf95208d4675beabe5be71a27edc38ec7ca1ead1a98d5712b902f']}
# print(data['NO_STORE'])
xml_data = data['Data']
# print(xml_data)
# for i in xml_data:
#     print ("序号：%s   值：%s" % (xml_data.index(i) + 1, i),'\n')
str_xml_data = xml_data[0]
# xml_file = open("data.xml","w")
# xml_file.write(str_xml_data)
# xml_file.close()
import xml.etree.ElementTree as ET
root = ET.fromstring(str_xml_data)
print(root.tag,'\n')

class sendCell:
    def __init__(self):
            self.barcode = ''     # 名称
            self.name = ''     # 尺寸
            self.telphone = ''     # 列表

dataToSend = []

for shipment in root:
    no_barcode_1 = ""
    no_barcode_2 = ""
    name = ""
    telphone = ""
    for child in shipment:
        # print(child.tag,child.text)
        if child.tag == 'NO_ECCODE1':
            no_barcode_1 = child.text
        if child.tag == 'NO_ECCODE2':
            no_barcode_2 = child.text
        if child.tag == 'NM_ORDER':
            name = child.text
        if child.tag == 'ID_TELCODE':
            telphone = child.text
    cell = sendCell()
    cell.barcode = no_barcode_1+no_barcode_2
    cell.name = name
    cell.telphone = telphone
    dataToSend.append(cell)
for ds in dataToSend:
    print(ds.barcode)
    print(ds.name)
    print(ds.telphone)

    # print(shipment.tag, shipment.attrib)
